// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/submit-closeup": {
    params: {};
  };
  "/submit-closeup/confirmation": {
    params: {};
  };
  "/ticket-print": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/submit-closeup" | "/submit-closeup/confirmation" | "/ticket-print";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/submit-closeup.jsx": {
    id: "routes/submit-closeup";
    page: "/submit-closeup";
  };
  "routes/confirmation.jsx": {
    id: "routes/confirmation";
    page: "/submit-closeup/confirmation";
  };
  "routes/ticket-print.jsx": {
    id: "routes/ticket-print";
    page: "/ticket-print";
  };
};